CUOR = CUOR or {}

CUOR.Consumables = {
    {
        key = "FLASK_BLINDING_LIGHT",
        label = "Flask of Blinding Light",
        itemID = 22861,
        enabled = false,
    },
    {
        key = "FLASK_FORTIFICATION",
        label = "Flask of Fortification",
        itemID = 22851,
        enabled = false,
    },
    {
        key = "FLASK_MIGHTY_RESTORATION",
        label = "Flask of Mighty Restoration",
        itemID = 22853,
        enabled = false,
    },
    {
        key = "FLASK_PURE_DEATH",
        label = "Flask of Pure Death",
        itemID = 22866,
        enabled = false,
    },
    {
        key = "FLASK_RELENTLESS_ASSAULT",
        label = "Flask of Relentless Assault",
        itemID = 22854,
        enabled = false,
    },
    {
        key = "FLASK_SUPREME_POWER",
        label = "Flask of Supreme Power",
        itemID = 13512,
        enabled = false,
    },
    {
        key = "ELIXIR_ADEPT",
        label = "Adept's Elixir",
        itemID = 28103,
        enabled = false,
    },
    {
        key = "ELIXIR_DEMONSLAYING",
        label = "Elixir of Demonslaying",
        itemID = 9224,
        enabled = false,
    },
    {
        key = "ELIXIR_DRAENIC_WISDOM",
        label = "Elixir of Draenic Wisdom",
        itemID = 32067,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_AGILITY",
        label = "Elixir of Major Agility",
        itemID = 22831,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_FIREPOWER",
        label = "Elixir of Major Firepower",
        itemID = 22833,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_FROST_POWER",
        label = "Elixir of Major Frost Power",
        itemID = 22834,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_SHADOW_POWER",
        label = "Elixir of Major Shadow Power",
        itemID = 22835,
        enabled = false,
    },
    {
        key = "ELIXIR_MASTERY",
        label = "Elixir of Mastery",
        itemID = 28104,
        enabled = false,
    },
    {
        key = "ELIXIR_ONSLAUGHT",
        label = "Elixir of Major Onslaught",
        itemID = 22832,
        enabled = false,
    },
    {
        key = "ELIXIR_HEALING_POWER",
        label = "Elixir of Healing Power",
        itemID = 22825,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_DEFENSE",
        label = "Elixir of Major Defense",
        itemID = 22840,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_MAGEBLOOD",
        label = "Elixir of Major Mageblood",
        itemID = 22841,
        enabled = false,
    },
    {
        key = "ELIXIR_MAJOR_FORTITUDE",
        label = "Elixir of Major Fortitude",
        itemID = 22828,
        enabled = false,
    },
    {
        key = "ELIXIR_IRONSKIN",
        label = "Elixir of Ironskin",
        itemID = 32068,
        enabled = false,
    },
    {
        key = "ELIXIR_DRAENIC_STRENGTH",
        label = "Elixir of Major Strength",
        itemID = 22824,
        enabled = false,
    },
    {
        key = "ELIXIR_MINOR_ACCURACY",
        label = "Elixir of Major Accuracy",
        itemID = 22826,
        enabled = false,
    },
    {
        key = "POTION_DESTRUCTION",
        label = "Destruction Potion",
        itemID = 22839,
        enabled = false,
    },
    {
        key = "POTION_HASTE",
        label = "Haste Potion",
        itemID = 22838,
        enabled = false,
    },
    {
        key = "POTION_IRONSHIELD",
        label = "Ironshield Potion",
        itemID = 22849,
        enabled = false,
    },
    {
        key = "POTION_MAJOR_DREAMLESS",
        label = "Major Dreamless Sleep Potion",
        itemID = 22836,
        enabled = false,
    },
    {
        key = "POTION_MAJOR_ARCANE",
        label = "Super Mana Potion",
        itemID = 22832,
        enabled = false,
    },
    {
        key = "POTION_MAJOR_HEALING",
        label = "Super Healing Potion",
        itemID = 22829,
        enabled = false,
    },
    {
        key = "POTION_HEROIC",
        label = "Heroic Potion",
        itemID = 22837,
        enabled = false,
    },
    {
        key = "POTION_MAD_ALCHEMIST",
        label = "Mad Alchemist's Potion",
        itemID = 34440,
        enabled = false,
    },
    {
        key = "POTION_NIGHTMARE_SEED",
        label = "Nightmare Seed",
        itemID = 22797,
        enabled = false,
    },
    {
        key = "POTION_FLAME_CAP",
        label = "Flame Cap",
        itemID = 22788,
        enabled = false,
    },
    {
        key = "WEAPON_SUPERIOR_WIZARD_OIL",
        label = "Superior Wizard Oil",
        itemID = 22522,
        enabled = false,
    },
    {
        key = "WEAPON_BRILLIANT_WIZARD_OIL",
        label = "Brilliant Wizard Oil",
        itemID = 20749,
        enabled = false,
    },
    {
        key = "WEAPON_SUPERIOR_MANA_OIL",
        label = "Superior Mana Oil",
        itemID = 22521,
        enabled = false,
    },
    {
        key = "WEAPON_BRILLIANT_MANA_OIL",
        label = "Brilliant Mana Oil",
        itemID = 20748,
        enabled = false,
    },
    {
        key = "WEAPON_ADAMANTITE_SHARPENING_STONE",
        label = "Adamantite Sharpening Stone",
        itemID = 23529,
        enabled = false,
    },
    {
        key = "WEAPON_FEL_SHARPENING_STONE",
        label = "Fel Sharpening Stone",
        itemID = 23528,
        enabled = false,
    },
    {
        key = "WEAPON_ADAMANTITE_WEIGHTSTONE",
        label = "Adamantite Weightstone",
        itemID = 28421,
        enabled = false,
    },
    {
        key = "WEAPON_FEL_WEIGHTSTONE",
        label = "Fel Weightstone",
        itemID = 23559,
        enabled = false,
    },
    {
        key = "FOOD_BLACKENED_BASILISK",
        label = "Blackened Basilisk",
        itemID = 27657,
        enabled = false,
    },
    {
        key = "FOOD_GRILLED_MUDFISH",
        label = "Grilled Mudfish",
        itemID = 27664,
        enabled = false,
    },
    {
        key = "FOOD_POACHED_BLUEFISH",
        label = "Poached Bluefish",
        itemID = 27665,
        enabled = false,
    },
    {
        key = "FOOD_RAVAGER_DOG",
        label = "Ravager Dog",
        itemID = 27655,
        enabled = false,
    },
    {
        key = "FOOD_ROASTED_CLEFTHOOF",
        label = "Roasted Clefthoof",
        itemID = 27658,
        enabled = false,
    },
    {
        key = "FOOD_SKULLFISH_SOUP",
        label = "Skullfish Soup",
        itemID = 33825,
        enabled = false,
    },
    {
        key = "FOOD_SPIDER_SAUSAGE",
        label = "Warp Burger",
        itemID = 27660,
        enabled = false,
    },
    {
        key = "FOOD_SPORELING_SNACK",
        label = "Spicy Crawdad",
        itemID = 33052,
        enabled = false,
    },
    {
        key = "FOOD_FISH_FEAST_STYLE",
        label = "Golden Fish Sticks",
        itemID = 27666,
        enabled = false,
    },
    {
        key = "FOOD_SPICY_HOT_TALBUK",
        label = "Spicy Hot Talbuk",
        itemID = 33872,
        enabled = false,
    },
    {
        key = "DRUMS_BATTLE",
        label = "Drums of Battle",
        itemID = 29529,
        enabled = false,
    },
    {
        key = "DRUMS_RESTORATION",
        label = "Drums of Restoration",
        itemID = 29531,
        enabled = false,
    },
    {
        key = "DRUMS_WAR",
        label = "Drums of War",
        itemID = 29530,
        enabled = false,
    },
    {
        key = "RUNE_DEMONIC",
        label = "Demonic Rune",
        itemID = 12662,
        enabled = false,
    },
    {
        key = "RUNE_DARK",
        label = "Dark Rune",
        itemID = 20520,
        enabled = false,
    },
    {
        key = "SCROLL_AGILITY_V",
        label = "Scroll of Agility V",
        itemID = 27498,
        enabled = false,
    },
    {
        key = "SCROLL_STRENGTH_V",
        label = "Scroll of Strength V",
        itemID = 27503,
        enabled = false,
    },
    {
        key = "SCROLL_STAMINA_V",
        label = "Scroll of Stamina V",
        itemID = 27501,
        enabled = false,
    },
    {
        key = "SCROLL_SPIRIT_V",
        label = "Scroll of Spirit V",
        itemID = 27504,
        enabled = false,
    },
    {
        key = "SCROLL_INTELLECT_V",
        label = "Scroll of Intellect V",
        itemID = 27499,
        enabled = false,
    },
    {
        key = "SCROLL_PROTECTION_V",
        label = "Scroll of Protection V",
        itemID = 27500,
        enabled = false,
    },
    {
        key = "BUFF_FEL_BLOSSOM",
        label = "Fel Blossom",
        itemID = 22795,
        enabled = false,
    },
    {
        key = "BUFF_HASTE_BROOCH",
        label = "Bloodberry Elixir",
        itemID = 32721,
        enabled = false,
    },
    {
        key = "RESIST_ARCANE",
        label = "Arcane Protection Potion",
        itemID = 13461,
        enabled = false,
    },
    {
        key = "RESIST_FIRE",
        label = "Fire Protection Potion",
        itemID = 13457,
        enabled = false,
    },
    {
        key = "RESIST_FROST",
        label = "Frost Protection Potion",
        itemID = 13456,
        enabled = false,
    },
    {
        key = "RESIST_NATURE",
        label = "Nature Protection Potion",
        itemID = 13458,
        enabled = false,
    },
    {
        key = "RESIST_SHADOW",
        label = "Shadow Protection Potion",
        itemID = 13459,
        enabled = false,
    },
}

CUOR.Settings = {
    priceSource = "AUCTIONATOR",
    allowTSMFallback = false,
    trackInRaidOnly = true,
    autoResetOnRaidEnter = true,
    framePoint = "CENTER",
    frameX = 0,
    frameY = 0,
    frameWidth = 340,
    rowHeight = 18,
    title = "Consumes Used On Riad",
}
